"""
Report Generator Module
Generates markdown and PDF reports
"""

from typing import Dict, List
from datetime import datetime
import markdown
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import io


class ReportGenerator:
    """Generates markdown and PDF reports"""
    
    def __init__(self):
        """Initialize report generator"""
        pass
    
    def generate_markdown(self, data: Dict) -> str:
        """
        Generate markdown report
        
        Args:
            data: Dictionary with all report data
            
        Returns:
            Markdown string
        """
        md = []
        
        # Header
        md.append("# AI-Driven Interview Report")
        md.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        md.append("---\n")
        
        # Executive Summary
        md.append("## Executive Summary\n")
        overall_score = data.get('final_scores', {}).get('overall_score', 0)
        md.append(f"**Overall Score:** {overall_score}/100\n")
        md.append(f"**Questions Asked:** {data.get('question_count', 0)}\n")
        md.append(f"**Interview Duration:** {data.get('duration', 'N/A')}\n\n")
        
        # Extracted Content
        md.append("## Extracted Content\n")
        md.append("### Screen Content\n")
        screen_text = data.get('context', {}).get('screen_text', 'No content extracted')
        md.append(f"```\n{screen_text[:500]}\n```\n\n")
        
        md.append("### Speech Transcript\n")
        speech_text = data.get('context', {}).get('speech_text', 'No speech transcribed')
        md.append(f"> {speech_text}\n\n")
        
        md.append("### Detected Keywords\n")
        keywords = data.get('context', {}).get('keywords', [])
        md.append(f"{', '.join(keywords[:20])}\n\n")
        
        # Interview Questions & Answers
        md.append("## Interview Q&A\n")
        qa_pairs = data.get('qa_pairs', [])
        for i, qa in enumerate(qa_pairs, 1):
            md.append(f"### Question {i}\n")
            md.append(f"**Q:** {qa['question']}\n\n")
            md.append(f"**A:** {qa['answer']}\n\n")
            md.append("---\n")
        
        # Scoring Breakdown
        md.append("## Scoring Breakdown\n")
        final_scores = data.get('final_scores', {})
        breakdown = final_scores.get('breakdown', {})
        rubric = final_scores.get('rubric', {})
        
        md.append("| Criterion | Score | Weight | Weighted Score | Description |\n")
        md.append("|-----------|-------|--------|----------------|-------------|\n")
        
        weighted_scores = final_scores.get('weighted_scores', {})
        for criterion, score in breakdown.items():
            weight = rubric.get(criterion, {}).get('weight', 0) * 100
            weighted = weighted_scores.get(criterion, 0)
            desc = rubric.get(criterion, {}).get('description', '')
            md.append(f"| {criterion.replace('_', ' ').title()} | {score:.1f} | {weight:.0f}% | {weighted:.2f} | {desc} |\n")
        
        md.append(f"\n**Overall Score:** {overall_score}/100\n\n")
        
        # Feedback
        feedback = data.get('feedback', {})
        md.append("## Feedback\n")
        
        md.append("### Strengths\n")
        strengths = feedback.get('strengths', [])
        if strengths:
            for strength in strengths:
                md.append(f"- **{strength['criterion']}** ({strength['score']}/100): {strength['description']}\n")
        else:
            md.append("- No specific strengths identified.\n")
        md.append("\n")
        
        md.append("### Areas for Improvement\n")
        weaknesses = feedback.get('weaknesses', [])
        if weaknesses:
            for weakness in weaknesses:
                md.append(f"- **{weakness['criterion']}** ({weakness['score']}/100): {weakness['description']}\n")
        else:
            md.append("- No major weaknesses identified.\n")
        md.append("\n")
        
        md.append("### Suggestions\n")
        suggestions = feedback.get('suggestions', [])
        for i, suggestion in enumerate(suggestions, 1):
            md.append(f"{i}. {suggestion}\n")
        md.append("\n")
        
        # Footer
        md.append("---\n")
        md.append("*Report generated by AI-Driven Automated Interviewer*\n")
        
        return "\n".join(md)
    
    def generate_pdf(self, data: Dict, output_path: str):
        """
        Generate PDF report
        
        Args:
            data: Dictionary with all report data
            output_path: Path to save PDF file
        """
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f4788'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c5aa0'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        # Title
        story.append(Paragraph("AI-Driven Interview Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", heading_style))
        overall_score = data.get('final_scores', {}).get('overall_score', 0)
        story.append(Paragraph(f"<b>Overall Score:</b> {overall_score}/100", styles['Normal']))
        story.append(Paragraph(f"<b>Questions Asked:</b> {data.get('question_count', 0)}", styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        # Extracted Content
        story.append(Paragraph("Extracted Content", heading_style))
        screen_text = data.get('context', {}).get('screen_text', 'No content extracted')[:500]
        story.append(Paragraph("<b>Screen Content:</b>", styles['Normal']))
        story.append(Paragraph(screen_text, styles['Normal']))
        story.append(Spacer(1, 0.1*inch))
        
        speech_text = data.get('context', {}).get('speech_text', 'No speech transcribed')
        story.append(Paragraph("<b>Speech Transcript:</b>", styles['Normal']))
        story.append(Paragraph(speech_text, styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        # Q&A
        story.append(Paragraph("Interview Q&A", heading_style))
        qa_pairs = data.get('qa_pairs', [])
        for i, qa in enumerate(qa_pairs, 1):
            story.append(Paragraph(f"<b>Question {i}:</b> {qa['question']}", styles['Normal']))
            story.append(Paragraph(f"<b>Answer:</b> {qa['answer']}", styles['Normal']))
            story.append(Spacer(1, 0.15*inch))
        
        # Scoring Table
        story.append(Paragraph("Scoring Breakdown", heading_style))
        final_scores = data.get('final_scores', {})
        breakdown = final_scores.get('breakdown', {})
        rubric = final_scores.get('rubric', {})
        weighted_scores = final_scores.get('weighted_scores', {})
        
        table_data = [['Criterion', 'Score', 'Weight', 'Weighted Score', 'Description']]
        for criterion, score in breakdown.items():
            weight = rubric.get(criterion, {}).get('weight', 0) * 100
            weighted = weighted_scores.get(criterion, 0)
            desc = rubric.get(criterion, {}).get('description', '')
            table_data.append([
                criterion.replace('_', ' ').title(),
                f"{score:.1f}",
                f"{weight:.0f}%",
                f"{weighted:.2f}",
                desc
            ])
        
        table = Table(table_data, colWidths=[1.5*inch, 0.8*inch, 0.8*inch, 1*inch, 2.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        story.append(table)
        story.append(Spacer(1, 0.2*inch))
        
        # Feedback
        story.append(Paragraph("Feedback", heading_style))
        feedback = data.get('feedback', {})
        
        story.append(Paragraph("<b>Strengths:</b>", styles['Normal']))
        strengths = feedback.get('strengths', [])
        if strengths:
            for strength in strengths:
                story.append(Paragraph(
                    f"• {strength['criterion']} ({strength['score']}/100): {strength['description']}",
                    styles['Normal']
                ))
        else:
            story.append(Paragraph("• No specific strengths identified.", styles['Normal']))
        story.append(Spacer(1, 0.15*inch))
        
        story.append(Paragraph("<b>Areas for Improvement:</b>", styles['Normal']))
        weaknesses = feedback.get('weaknesses', [])
        if weaknesses:
            for weakness in weaknesses:
                story.append(Paragraph(
                    f"• {weakness['criterion']} ({weakness['score']}/100): {weakness['description']}",
                    styles['Normal']
                ))
        else:
            story.append(Paragraph("• No major weaknesses identified.", styles['Normal']))
        story.append(Spacer(1, 0.15*inch))
        
        story.append(Paragraph("<b>Suggestions:</b>", styles['Normal']))
        suggestions = feedback.get('suggestions', [])
        for i, suggestion in enumerate(suggestions, 1):
            story.append(Paragraph(f"{i}. {suggestion}", styles['Normal']))
        
        # Build PDF
        doc.build(story)
    
    def save_markdown(self, markdown_content: str, output_path: str):
        """Save markdown content to file"""
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(markdown_content)

